### ISSUE TITLE
How can we get the percentage of matching for query string

### ISSUE THREAD

**Issue by priyankagutte** [dorianbrown/rank_bm25#12]
How can we get the Percentage of matching and its index value in a list for query string.

**Comment by lavarthan** [comment]
I don't think there is any straight way, but you can get the all scores and you can match with your results. for example
`doc_scores = bm25.get_scores(tokenized_query)
  doc_scores.sort()
  doc_scores = doc_scores[::-1]`

here doc_scores will be sorted so you can know the matching score of your each doc
