### ISSUE TITLE
Mistake in the description

### ISSUE THREAD

**Issue by BochkarevV** [dorianbrown/rank_bm25#2]
Hello Dorian!
A very nice and simple implementation of the algorithms! 

However, if you just copy the code from the doc and try to run it, it doesn't work, producing a vector of three 0's.

Here is what needs to be changed:
`bm25 = BM25Okapi(corpus)`
should actually be
`bm25 = BM25Okapi(tokenized_corpus)`

It works well after this minor change.

**Comment by dorianbrown** [comment]
Thanks for taking the time to create this issue, I completely missed that! 

Should be fixed now.
