### ISSUE TITLE
How can i query with boolean operators ?

### ISSUE THREAD

**Issue by Adeel-Intizar** [dorianbrown/rank_bm25#22]
Hi, how can i query text with boolean operators like " windy london and new york", " england or scotland" etc.

Thanks

**Comment by dorianbrown** [comment]
Using boolean operators in queries in the way you described isn't currently part of this libraries functionality. That said, if there's enough interest I think it could be worth looking into to implement.

In the meantime I'll mark this as a feature enhancement request.
