### ISSUE TITLE
Unable to import BM250kapi

### ISSUE THREAD

**Issue by ayush-1506** [dorianbrown/rank_bm25#3]
```
>>> from rank_bm25 import BM250kapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'BM250kapi' from 'rank_bm25' (/Users/ayush99/github/bbug/lib/python3.7/site-packages/rank_bm25.py)
```

**Comment by dorianbrown** [comment]
The problem is its BM25 Okapi, and not BM250 kapi. If you use an `O` instead of a `0`, it should work.

**Comment by ayush-1506** [comment]
Ahh, my bad. Thanks for that. Closing the issue.

**Comment by dorianbrown** [comment]
I just created a fresh environment, installed `rank_bm25` from pip, and ran `from rank_bm25 import BM25Okapi` without any issues.

Could you describe the steps you took (ie make a minimum reproducible example), and also share the error the was given when you tried importing?
